trigger: 
 - master

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  displayName: Setup go
  inputs:
    version: '1.13.5'
- task: Go@0
  displayName: Download dependencies
  inputs:
    command: 'custom'
    customCommand: 'mod'
    arguments: 'download'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  displayName: Run tests
  inputs:
    command: 'test'
    arguments: '-v ./...'
    workingDirectory: '$(System.DefaultWorkingDirectory)'