name: Module Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Setup Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    
    - name: Setup Terraform 0.13.X
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ^0.13
        
    - name: Get dependencies
      run: |
        go mod download

    - name: Run tests
      run: |
        go test ./... -v
  
  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Run semantic-release
        run: |
          npm install
          npx semantic-release