name: Test workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Setup Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    
    - name: Setup Terraform 0.13.X
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ^0.13

    - name: Setup env
      run: |
        echo "$(go env GOPATH)/bin >> $GITHUB_PATH"
      shell: bash

    - name: Get dependencies
      run: |
        go mod download

    - name: Run tests
      run: |
        PACKAGE_NAMES=$(go list ./...)
        gotestsum --format testname --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES