name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.13'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '^0.13'

    - name: Install gotestsum
      run: curl -sSL "https://github.com/gotestyourself/gotestsum/releases/download/v0.6.0/gotestsum_0.6.0_linux_amd64.tar.gz" | sudo tar -xz -C /usr/local/bin gotestsum

    - name: Get dependencies
      run: |
        go mod download
    
    - name: Run terratest
      run: |
        PACKAGE_NAMES=$(go list ./...)
        gotestsum --format testname --junitfile gotestsum-report.xml -- $PACKAGE_NAMES
